################################################################################
Concuerror started with options:
  [{after_timeout,infinity},
   {assume_racing,false},
   {delay_bound,infinity},
   {depth_bound,5000},
   {entry_point,{ets_delete_object,test3,[]}},
   {files,["/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"]},
   {ignore_error,[]},
   {ignore_first_crash,true},
   {instant_delivery,false},
   {non_racing_system,[]},
   {optimal,true},
   {print_depth,20},
   {quiet,true},
   {scheduling,round_robin},
   {show_races,false},
   {strict_scheduling,false},
   {symbolic_names,true},
   {timeout,infinity},
   {treat_as_normal,[]}]
################################################################################
Erroneous interleaving 1:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  11: P.2: exits normally
  12: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  13: P.3: exits normally
  14: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  15: P.4: exits normally
  16: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  17: P.5: exits normally
  18: P.6: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  19: P.6: exits normally
################################################################################
Erroneous interleaving 2:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  11: P.2: exits normally
  12: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  13: P.3: exits normally
  14: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  15: P.4: exits normally
  16: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  17: P.6: exits normally
  18: P.5: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  19: P.5: exits normally
################################################################################
Erroneous interleaving 3:
* At step 15 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 17 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  11: P.2: exits normally
  12: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  13: P.3: exits normally
  14: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  15: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  16: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  17: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  18: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  19: P.4: exits normally
################################################################################
Erroneous interleaving 4:
* At step 15 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  11: P.2: exits normally
  12: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  13: P.3: exits normally
  14: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  15: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  16: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  17: P.4: exits normally
  18: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  19: P.6: exits normally
################################################################################
Erroneous interleaving 5:
* At step 15 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  11: P.2: exits normally
  12: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  13: P.3: exits normally
  14: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  15: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  16: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  17: P.4: exits normally
  18: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  19: P.5: exits normally
################################################################################
Erroneous interleaving 6:
* At step 15 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 17 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  11: P.2: exits normally
  12: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  13: P.3: exits normally
  14: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  15: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  16: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  17: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  18: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  19: P.4: exits normally
################################################################################
Erroneous interleaving 7:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  13: P.4: exits normally
  14: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  15: P.5: exits normally
  16: P.6: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  17: P.6: exits normally
  18: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  19: P.2: exits normally
################################################################################
Erroneous interleaving 8:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  13: P.4: exits normally
  14: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  15: P.5: exits normally
  16: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  17: P.2: exits normally
  18: P.6: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  19: P.6: exits normally
################################################################################
Erroneous interleaving 9:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  13: P.4: exits normally
  14: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  15: P.6: exits normally
  16: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  17: P.2: exits normally
  18: P.5: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  19: P.5: exits normally
################################################################################
Erroneous interleaving 10:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  13: P.4: exits normally
  14: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  15: P.6: exits normally
  16: P.5: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  17: P.5: exits normally
  18: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  19: P.2: exits normally
################################################################################
Erroneous interleaving 11:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  13: P.4: exits normally
  14: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  15: P.2: exits normally
  16: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  17: P.5: exits normally
  18: P.6: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  19: P.6: exits normally
################################################################################
Erroneous interleaving 12:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  13: P.4: exits normally
  14: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  15: P.2: exits normally
  16: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  17: P.6: exits normally
  18: P.5: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  19: P.5: exits normally
################################################################################
Erroneous interleaving 13:
* At step 13 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 15 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  13: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  15: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  16: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  17: P.2: exits normally
  18: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  19: P.4: exits normally
################################################################################
Erroneous interleaving 14:
* At step 13 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 15 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  13: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  15: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  16: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  17: P.4: exits normally
  18: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  19: P.2: exits normally
################################################################################
Erroneous interleaving 15:
* At step 13 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  13: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  15: P.2: exits normally
  16: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  17: P.4: exits normally
  18: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  19: P.6: exits normally
################################################################################
Erroneous interleaving 16:
* At step 13 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 17 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  13: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  15: P.2: exits normally
  16: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  17: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  18: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  19: P.4: exits normally
################################################################################
Erroneous interleaving 17:
* At step 13 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  13: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  15: P.4: exits normally
  16: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  17: P.6: exits normally
  18: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  19: P.2: exits normally
################################################################################
Erroneous interleaving 18:
* At step 13 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  13: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  15: P.4: exits normally
  16: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  17: P.2: exits normally
  18: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  19: P.6: exits normally
################################################################################
Erroneous interleaving 19:
* At step 13 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  13: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  15: P.2: exits normally
  16: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  17: P.4: exits normally
  18: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  19: P.5: exits normally
################################################################################
Erroneous interleaving 20:
* At step 13 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 17 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  13: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  15: P.2: exits normally
  16: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  17: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  18: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  19: P.4: exits normally
################################################################################
Erroneous interleaving 21:
* At step 13 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  13: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  15: P.4: exits normally
  16: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  17: P.5: exits normally
  18: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  19: P.2: exits normally
################################################################################
Erroneous interleaving 22:
* At step 13 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  13: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  15: P.4: exits normally
  16: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  17: P.2: exits normally
  18: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  19: P.5: exits normally
################################################################################
Erroneous interleaving 23:
* At step 13 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 15 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  13: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  15: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  16: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  17: P.2: exits normally
  18: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  19: P.4: exits normally
################################################################################
Erroneous interleaving 24:
* At step 13 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 15 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
   9: P.1: exits normally
  10: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  11: P.3: exits normally
  12: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  13: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  15: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  16: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  17: P.4: exits normally
  18: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  19: P.2: exits normally
################################################################################
Erroneous interleaving 25:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
   9: P.2: exits normally
  10: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  11: P.4: exits normally
  12: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  13: P.5: exits normally
  14: P.6: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  15: P.6: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 26:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
   9: P.2: exits normally
  10: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  11: P.4: exits normally
  12: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  13: P.6: exits normally
  14: P.5: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  15: P.5: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 27:
* At step 11 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 13 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
   9: P.2: exits normally
  10: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  11: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  12: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  13: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  15: P.4: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 28:
* At step 11 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
   9: P.2: exits normally
  10: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  11: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  12: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  13: P.4: exits normally
  14: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  15: P.6: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 29:
* At step 11 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
   9: P.2: exits normally
  10: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  11: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  12: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  13: P.4: exits normally
  14: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  15: P.5: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 30:
* At step 11 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 13 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
   9: P.2: exits normally
  10: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  11: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  12: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  13: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  15: P.4: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 31:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
   9: P.4: exits normally
  10: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  11: P.5: exits normally
  12: P.6: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  13: P.6: exits normally
  14: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  15: P.2: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 32:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
   9: P.4: exits normally
  10: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  11: P.5: exits normally
  12: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  13: P.2: exits normally
  14: P.6: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  15: P.6: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 33:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
   9: P.4: exits normally
  10: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  11: P.6: exits normally
  12: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  13: P.2: exits normally
  14: P.5: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  15: P.5: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 34:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
   9: P.4: exits normally
  10: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  11: P.6: exits normally
  12: P.5: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  13: P.5: exits normally
  14: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  15: P.2: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 35:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
   9: P.4: exits normally
  10: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  11: P.2: exits normally
  12: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  13: P.5: exits normally
  14: P.6: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  15: P.6: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 36:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
   9: P.4: exits normally
  10: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  11: P.2: exits normally
  12: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  13: P.6: exits normally
  14: P.5: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  15: P.5: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 37:
* At step 9 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 11 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
   9: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  11: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  12: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  13: P.2: exits normally
  14: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  15: P.4: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 38:
* At step 9 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 11 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
   9: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  11: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  12: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  13: P.4: exits normally
  14: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  15: P.2: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 39:
* At step 9 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
   9: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  11: P.2: exits normally
  12: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  13: P.4: exits normally
  14: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  15: P.6: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 40:
* At step 9 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 13 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
   9: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  11: P.2: exits normally
  12: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  13: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  15: P.4: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 41:
* At step 9 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
   9: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  11: P.4: exits normally
  12: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  13: P.6: exits normally
  14: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  15: P.2: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 42:
* At step 9 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
   9: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  11: P.4: exits normally
  12: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  13: P.2: exits normally
  14: P.6: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
  15: P.6: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 43:
* At step 9 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
   9: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  11: P.2: exits normally
  12: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  13: P.4: exits normally
  14: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  15: P.5: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 44:
* At step 9 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 13 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
   9: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  11: P.2: exits normally
  12: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  13: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  14: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  15: P.4: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 45:
* At step 9 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
   9: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  11: P.4: exits normally
  12: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  13: P.5: exits normally
  14: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  15: P.2: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 46:
* At step 9 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
   9: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  11: P.4: exits normally
  12: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  13: P.2: exits normally
  14: P.5: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  15: P.5: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 47:
* At step 9 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 11 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
   9: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  11: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  12: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  13: P.2: exits normally
  14: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  15: P.4: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Erroneous interleaving 48:
* At step 9 process P.6 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [34,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [34,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 11 process P.5 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [33,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [33,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 35
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 26
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.9.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.10.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.11.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.12.95948049>,[]])
    in erlang.erl line 2329
   6: P: P.5 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.13.95948049>,[]])
    in erlang.erl line 2329
   7: P: P.6 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.14.95948049>,[]])
    in erlang.erl line 2329
   8: P.6: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 34
   9: P.6: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[34,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.5: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 33
  11: P.5: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[33,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  12: P.4: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 32
  13: P.4: exits normally
  14: P.2: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 30
  15: P.2: exits normally
  16: P.3: [] = ets:lookup(table, foo)
    in ets_delete_object.erl line 31
  17: P.3: exits normally
  18: P.1: true = ets:delete_object(table, {foo,1})
    in ets_delete_object.erl line 29
  19: P.1: exits normally
################################################################################
Info:
--------------------------------------------------------------------------------
Instrumented ets_delete_object
Instrumented io_lib
Instrumented erlang
################################################################################
Done! (Exit status: completed)
  Summary: 48 errors, 48/48 interleavings explored
