################################################################################
Concuerror started with options:
  [{after_timeout,infinity},
   {assume_racing,false},
   {delay_bound,infinity},
   {depth_bound,5000},
   {entry_point,{ets_delete_object,test2,[]}},
   {files,["/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"]},
   {ignore_error,[]},
   {ignore_first_crash,true},
   {instant_delivery,false},
   {non_racing_system,[]},
   {optimal,true},
   {print_depth,20},
   {quiet,true},
   {scheduling,round_robin},
   {show_races,false},
   {strict_scheduling,false},
   {symbolic_names,true},
   {timeout,infinity},
   {treat_as_normal,[]}]
################################################################################
Erroneous interleaving 1:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
   7: P.1: exits normally
   8: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
   9: P.2: exits normally
  10: P.3: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
  11: P.3: exits normally
  12: P.4: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
  13: P.4: exits normally
################################################################################
Erroneous interleaving 2:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
   7: P.1: exits normally
   8: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
   9: P.2: exits normally
  10: P.4: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
  11: P.4: exits normally
  12: P.3: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
  13: P.3: exits normally
################################################################################
Erroneous interleaving 3:
* At step 9 process P.3 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [21,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [21,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 11 process P.4 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [22,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [22,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
   7: P.1: exits normally
   8: P.3: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
   9: P.3: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[21,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.4: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
  11: P.4: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[22,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  12: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
  13: P.2: exits normally
################################################################################
Erroneous interleaving 4:
* At step 9 process P.3 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [21,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [21,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
   7: P.1: exits normally
   8: P.3: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
   9: P.3: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[21,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
  11: P.2: exits normally
  12: P.4: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
  13: P.4: exits normally
################################################################################
Erroneous interleaving 5:
* At step 9 process P.4 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [22,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [22,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
   7: P.1: exits normally
   8: P.4: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
   9: P.4: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[22,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
  11: P.2: exits normally
  12: P.3: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
  13: P.3: exits normally
################################################################################
Erroneous interleaving 6:
* At step 9 process P.4 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [22,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [22,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 11 process P.3 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [21,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [21,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
   7: P.1: exits normally
   8: P.4: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
   9: P.4: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[22,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.3: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
  11: P.3: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[21,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  12: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
  13: P.2: exits normally
################################################################################
Erroneous interleaving 7:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
   7: P.2: exits normally
   8: P.3: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
   9: P.3: exits normally
  10: P.4: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
  11: P.4: exits normally
  12: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
  13: P.1: exits normally
################################################################################
Erroneous interleaving 8:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
   7: P.2: exits normally
   8: P.3: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
   9: P.3: exits normally
  10: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
  11: P.1: exits normally
  12: P.4: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
  13: P.4: exits normally
################################################################################
Erroneous interleaving 9:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
   7: P.2: exits normally
   8: P.4: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
   9: P.4: exits normally
  10: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
  11: P.1: exits normally
  12: P.3: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
  13: P.3: exits normally
################################################################################
Erroneous interleaving 10:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
   7: P.2: exits normally
   8: P.4: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
   9: P.4: exits normally
  10: P.3: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
  11: P.3: exits normally
  12: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
  13: P.1: exits normally
################################################################################
Erroneous interleaving 11:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
   7: P.2: exits normally
   8: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
   9: P.1: exits normally
  10: P.3: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
  11: P.3: exits normally
  12: P.4: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
  13: P.4: exits normally
################################################################################
Erroneous interleaving 12:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
   7: P.2: exits normally
   8: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
   9: P.1: exits normally
  10: P.4: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
  11: P.4: exits normally
  12: P.3: 4 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
  13: P.3: exits normally
################################################################################
Erroneous interleaving 13:
* At step 7 process P.3 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [21,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [21,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 9 process P.4 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [22,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [22,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.3: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
   7: P.3: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[21,{file,[47,104,111,109,101,47,115,116|...]}]}]})
   8: P.4: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
   9: P.4: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[22,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
  11: P.1: exits normally
  12: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
  13: P.2: exits normally
################################################################################
Erroneous interleaving 14:
* At step 7 process P.3 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [21,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [21,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 9 process P.4 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [22,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [22,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.3: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
   7: P.3: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[21,{file,[47,104,111,109,101,47,115,116|...]}]}]})
   8: P.4: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
   9: P.4: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[22,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
  11: P.2: exits normally
  12: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
  13: P.1: exits normally
################################################################################
Erroneous interleaving 15:
* At step 7 process P.3 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [21,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [21,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.3: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
   7: P.3: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[21,{file,[47,104,111,109,101,47,115,116|...]}]}]})
   8: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
   9: P.1: exits normally
  10: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
  11: P.2: exits normally
  12: P.4: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
  13: P.4: exits normally
################################################################################
Erroneous interleaving 16:
* At step 7 process P.3 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [21,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [21,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 11 process P.4 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [22,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [22,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.3: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
   7: P.3: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[21,{file,[47,104,111,109,101,47,115,116|...]}]}]})
   8: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
   9: P.1: exits normally
  10: P.4: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
  11: P.4: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[22,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  12: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
  13: P.2: exits normally
################################################################################
Erroneous interleaving 17:
* At step 7 process P.3 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [21,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [21,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.3: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
   7: P.3: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[21,{file,[47,104,111,109,101,47,115,116|...]}]}]})
   8: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
   9: P.2: exits normally
  10: P.4: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
  11: P.4: exits normally
  12: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
  13: P.1: exits normally
################################################################################
Erroneous interleaving 18:
* At step 7 process P.3 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [21,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [21,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.3: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
   7: P.3: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[21,{file,[47,104,111,109,101,47,115,116|...]}]}]})
   8: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
   9: P.2: exits normally
  10: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
  11: P.1: exits normally
  12: P.4: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
  13: P.4: exits normally
################################################################################
Erroneous interleaving 19:
* At step 7 process P.4 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [22,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [22,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.4: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
   7: P.4: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[22,{file,[47,104,111,109,101,47,115,116|...]}]}]})
   8: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
   9: P.1: exits normally
  10: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
  11: P.2: exits normally
  12: P.3: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
  13: P.3: exits normally
################################################################################
Erroneous interleaving 20:
* At step 7 process P.4 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [22,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [22,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 11 process P.3 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [21,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [21,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.4: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
   7: P.4: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[22,{file,[47,104,111,109,101,47,115,116|...]}]}]})
   8: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
   9: P.1: exits normally
  10: P.3: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
  11: P.3: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[21,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  12: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
  13: P.2: exits normally
################################################################################
Erroneous interleaving 21:
* At step 7 process P.4 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [22,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [22,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.4: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
   7: P.4: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[22,{file,[47,104,111,109,101,47,115,116|...]}]}]})
   8: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
   9: P.2: exits normally
  10: P.3: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
  11: P.3: exits normally
  12: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
  13: P.1: exits normally
################################################################################
Erroneous interleaving 22:
* At step 7 process P.4 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [22,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [22,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.4: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
   7: P.4: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[22,{file,[47,104,111,109,101,47,115,116|...]}]}]})
   8: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
   9: P.2: exits normally
  10: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
  11: P.1: exits normally
  12: P.3: 3 = ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
  13: P.3: exits normally
################################################################################
Erroneous interleaving 23:
* At step 7 process P.4 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [22,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [22,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 9 process P.3 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [21,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [21,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.4: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
   7: P.4: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[22,{file,[47,104,111,109,101,47,115,116|...]}]}]})
   8: P.3: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
   9: P.3: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[21,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
  11: P.1: exits normally
  12: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
  13: P.2: exits normally
################################################################################
Erroneous interleaving 24:
* At step 7 process P.4 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [22,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [22,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* At step 9 process P.3 exited abnormally
    Reason:
      {badarg,[{ets,update_counter,
                    [table,bar,1],
                    [21,
                     {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]}
    Stacktrace:
      [{ets,update_counter,
            [table,bar,1],
            [21,
             {file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/ets_delete_object.erl"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_delete_object.erl line 23
--------------------------------------------------------------------------------
Interleaving info:
   1: P: table = ets:new(table, [named_table,public])
    in ets_delete_object.erl line 17
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.4.95948049>,[]])
    in erlang.erl line 2329
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.5.95948049>,[]])
    in erlang.erl line 2329
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.6.95948049>,[]])
    in erlang.erl line 2329
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<ets_delete_object.7.95948049>,[]])
    in erlang.erl line 2329
   6: P.4: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 22
   7: P.4: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[22,{file,[47,104,111,109,101,47,115,116|...]}]}]})
   8: P.3: Exception badarg raised by: ets:update_counter(table, bar, 1)
    in ets_delete_object.erl line 21
   9: P.3: exits abnormally ({badarg,[{ets,update_counter,[table,bar,1],[21,{file,[47,104,111,109,101,47,115,116|...]}]}]})
  10: P.2: true = ets:insert(table, {bar,2})
    in ets_delete_object.erl line 20
  11: P.2: exits normally
  12: P.1: true = ets:delete_object(table, {bar,1})
    in ets_delete_object.erl line 19
  13: P.1: exits normally
################################################################################
Info:
--------------------------------------------------------------------------------
Instrumented ets_delete_object
Instrumented io_lib
Instrumented erlang
################################################################################
Done! (Exit status: completed)
  Summary: 24 errors, 24/24 interleavings explored
