################################################################################
Concuerror started with options:
  [{'after-timeout',infinite},
   {assume_racing,false},
   {files,["/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"]},
   {normal_exit,[normal]},
   {symbolic,true},
   {target,{trigger_the_after,trigger_the_after,[]}},
   {verbose,0},
   {wait,2000}]
################################################################################
Erroneous interleaving 1:
* At step 4 process P exited abnormally
    Reason:
      {error,
          [{trigger_the_after,trigger_the_after,0,
               [{file,
                    "/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                {line,12}]}]}
    Stacktrace:
      [{trigger_the_after,trigger_the_after,0,
                          [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                           {line,12}]}]
* At step 12 process P.1 exited abnormally
    Reason:
      {{nocatch,both},
       [{trigger_the_after,receive_two,0,
                           [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                            {line,18}]}]}
    Stacktrace:
      [{trigger_the_after,receive_two,0,
                          [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                           {line,18}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<trigger_the_after.0.103202625>,[]])
    in erlang.erl line 2329
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<trigger_the_after.3.103202625>,[]])
    in erlang.erl line 2329
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<trigger_the_after.3.103202625>,[]])
    in erlang.erl line 2329
   4: P: exits abnormally ({error,[{trigger_the_after,trigger_the_after,0,[{file,[47,104,111,109,101,47,115,116,97,118,114,111,115,47,103,105,116,47,67,111,110,99,117,101,114,114,111,114,47,116,101,115,116,115,47,115,117,105,116,101,115,47,98,97,115,105,99,95,116,101,115,116,115,47,115,114,99,47,116,114,105,103,103,101,114,95,116,104,101,95,97,102,116,101,114,46,101,114,108]},{line,12}]}]})
   5: P.2: two = P.1 ! two
    in trigger_the_after.erl line 25
   6: Message (two) from P.2 reaches P.1
   7: P.2: exits normally
   8: P.3: one = P.1 ! one
    in trigger_the_after.erl line 25
   9: Message (one) from P.3 reaches P.1
  10: P.1: receives message (one)
    in trigger_the_after.erl line 15
  11: P.1: receives message (two)
    in trigger_the_after.erl line 17
  12: P.1: exits abnormally ({{nocatch,both},[{trigger_the_after,receive_two,0,[{file,[47,104,111,109,101,47,115,116,97,118,114,111,115,47,103,105,116,47,67,111,110,99,117,101,114,114,111,114,47,116,101,115,116,115,47,115,117,105,116,101,115,47,98,97,115,105,99,95,116,101,115,116,115,47,115,114,99,47,116,114,105,103,103,101,114,95,116,104,101,95,97,102,116,101,114,46,101,114,108]},{line,18}]}]})
  13: P.3: exits normally
################################################################################
Erroneous interleaving 2:
* At step 4 process P exited abnormally
    Reason:
      {error,
          [{trigger_the_after,trigger_the_after,0,
               [{file,
                    "/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                {line,12}]}]}
    Stacktrace:
      [{trigger_the_after,trigger_the_after,0,
                          [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                           {line,12}]}]
* At step 13 process P.1 exited abnormally
    Reason:
      {{nocatch,one},
       [{trigger_the_after,receive_two,0,
                           [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                            {line,20}]}]}
    Stacktrace:
      [{trigger_the_after,receive_two,0,
                          [{file,"/home/stavros/git/Concuerror/tests/suites/basic_tests/src/trigger_the_after.erl"},
                           {line,20}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<trigger_the_after.0.103202625>,[]])
    in erlang.erl line 2329
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<trigger_the_after.3.103202625>,[]])
    in erlang.erl line 2329
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<trigger_the_after.3.103202625>,[]])
    in erlang.erl line 2329
   4: P: exits abnormally ({error,[{trigger_the_after,trigger_the_after,0,[{file,[47,104,111,109,101,47,115,116,97,118,114,111,115,47,103,105,116,47,67,111,110,99,117,101,114,114,111,114,47,116,101,115,116,115,47,115,117,105,116,101,115,47,98,97,115,105,99,95,116,101,115,116,115,47,115,114,99,47,116,114,105,103,103,101,114,95,116,104,101,95,97,102,116,101,114,46,101,114,108]},{line,12}]}]})
   5: P.2: two = P.1 ! two
    in trigger_the_after.erl line 25
   6: P.2: exits normally
   7: P.3: one = P.1 ! one
    in trigger_the_after.erl line 25
   8: Message (one) from P.3 reaches P.1
   9: P.1: receives message (one)
    in trigger_the_after.erl line 15
  10: P.3: exits normally
  11: P.1: receive timeout expired after 100 ms
    in trigger_the_after.erl line 17
  12: Message (two) from P.2 reaches P.1
  13: P.1: exits abnormally ({{nocatch,one},[{trigger_the_after,receive_two,0,[{file,[47,104,111,109,101,47,115,116,97,118,114,111,115,47,103,105,116,47,67,111,110,99,117,101,114,114,111,114,47,116,101,115,116,115,47,115,117,105,116,101,115,47,98,97,115,105,99,95,116,101,115,116,115,47,115,114,99,47,116,114,105,103,103,101,114,95,116,104,101,95,97,102,116,101,114,46,101,114,108]},{line,20}]}]})
################################################################################
Done! (Exit status: completed)
  Summary: 2 errors, 2/2 interleavings explored
