################################################################################
Concuerror started with options:
  [{target,{ets_new_failure_2,ets_new_failure_2,[]}},
   {symbolic,true},
   {verbose,0},
   {timeout,1000},
   {files,["/home/stavros/git/Concuerror/testsuite/suites/dpor/src/ets_new_failure_2.erl"]},
   {'after-timeout',infinite},
   {bound,2},
   {distributed,true},
   {'light-dpor',false}]
################################################################################
Erroneous interleaving 1:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_new_failure_2.erl line 22
    P.1 in ets_new_failure_2.erl line 14
* At step 8 process P.2 exited abnormally
    Reason:
      {badarg,
          [{ets,new,
               [table,[named_table,public]],
               [12,
                {file,
                    "/home/stavros/git/Concuerror/testsuite/suites/dpor/src/ets_new_failure_2.erl"}]},
           {ets_new_failure_2,'-ets_new_failure_2/0-fun-0-',1,
               [{file,
                    "/home/stavros/git/Concuerror/testsuite/suites/dpor/src/ets_new_failure_2.erl"},
                {line,12}]}]}
    Stacktrace:
      [{ets,new,
            [table,[named_table,public]],
            [12,
             {file,"/home/stavros/git/Concuerror/testsuite/suites/dpor/src/ets_new_failure_2.erl"}]},
       {ets_new_failure_2,'-ets_new_failure_2/0-fun-0-',1,
                          [{file,"/home/stavros/git/Concuerror/testsuite/suites/dpor/src/ets_new_failure_2.erl"},
                           {line,12}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_new_failure_2.0.124271153>,[]])
    in erlang.erl line 2329
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_new_failure_2.0.124271153>,[]])
    in erlang.erl line 2329
   3: P.1: table = ets:new(table, [named_table,public])
    in ets_new_failure_2.erl line 12
   4: P.1: ok = P ! ok
    in ets_new_failure_2.erl line 13
   5: Message (ok) from P.1 reaches P
   6: P: receives message (ok)
    in ets_new_failure_2.erl line 20
   7: P.2: Exception raised by: ets:new(table, [named_table,public])
    in ets_new_failure_2.erl line 12
   8: P.2: exits abnormally
################################################################################
Erroneous interleaving 2:
* Blocked at a 'receive' (when all other processes have exited):
    P in ets_new_failure_2.erl line 20
* At step 7 process P.2 exited abnormally
    Reason:
      {badarg,
          [{ets,new,
               [table,[named_table,public]],
               [12,
                {file,
                    "/home/stavros/git/Concuerror/testsuite/suites/dpor/src/ets_new_failure_2.erl"}]},
           {ets_new_failure_2,'-ets_new_failure_2/0-fun-0-',1,
               [{file,
                    "/home/stavros/git/Concuerror/testsuite/suites/dpor/src/ets_new_failure_2.erl"},
                {line,12}]}]}
    Stacktrace:
      [{ets,new,
            [table,[named_table,public]],
            [12,
             {file,"/home/stavros/git/Concuerror/testsuite/suites/dpor/src/ets_new_failure_2.erl"}]},
       {ets_new_failure_2,'-ets_new_failure_2/0-fun-0-',1,
                          [{file,"/home/stavros/git/Concuerror/testsuite/suites/dpor/src/ets_new_failure_2.erl"},
                           {line,12}]}]
* At step 5 process P.1 exited abnormally
    Reason:
      {badarg,
          [{ets,new,
               [table,[named_table,public]],
               [12,
                {file,
                    "/home/stavros/git/Concuerror/testsuite/suites/dpor/src/ets_new_failure_2.erl"}]},
           {ets_new_failure_2,'-ets_new_failure_2/0-fun-0-',1,
               [{file,
                    "/home/stavros/git/Concuerror/testsuite/suites/dpor/src/ets_new_failure_2.erl"},
                {line,12}]}]}
    Stacktrace:
      [{ets,new,
            [table,[named_table,public]],
            [12,
             {file,"/home/stavros/git/Concuerror/testsuite/suites/dpor/src/ets_new_failure_2.erl"}]},
       {ets_new_failure_2,'-ets_new_failure_2/0-fun-0-',1,
                          [{file,"/home/stavros/git/Concuerror/testsuite/suites/dpor/src/ets_new_failure_2.erl"},
                           {line,12}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<ets_new_failure_2.0.124271153>,[]])
    in erlang.erl line 2329
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<ets_new_failure_2.0.124271153>,[]])
    in erlang.erl line 2329
   3: P.2: Exception raised by: ets:new(table, [named_table,public])
    in ets_new_failure_2.erl line 12
   4: P.1: Exception raised by: ets:new(table, [named_table,public])
    in ets_new_failure_2.erl line 12
   5: P.1: exits abnormally
   6: P.1: true = ets:delete(table)
    (while exiting)
   7: P.2: exits abnormally
################################################################################
Done! (Exit status: ok)
  Summary: 2 errors, 2/2 interleavings explored
